<a href="https://colab.research.google.com/github/etgonehomie/portfolio/blob/main/PyTorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.4.0+cu121


# Introduction to Tensors

In [2]:
# `.rand` creates a random tensor with size defined
t1 = torch.rand(2,3)
t2 = torch.rand(3,2)
t_combine = t1 @ t2   # matrix multiplication

print(t_combine)

tensor([[0.6922, 0.6006],
        [0.9691, 0.5689]])


In [3]:
# TODO: How to do a dot multiplication for higher values
# http://matrixmultiplication.xyz/ <- Visualization for 2d matrix
t3 = torch.rand(3,4,5,9)
t4 = torch.rand(9,7)
t2_combine = t3 @ t4
print(t_combine)

tensor([[0.6922, 0.6006],
        [0.9691, 0.5689]])


In [4]:
# Tensors with 0s or 1s
zeros = torch.zeros(4,5)
ones = torch.ones(4,5)
print(ones)
print(zeros)

# Tensors within a range
tensor_r = torch.range(start=1, end=10, step=1)
print(tensor_r)

# To get a tensor shape and make it all zeros or ones
zeros_like = torch.zeros_like(t1)
ones_like = torch.ones_like(t2)
print(zeros_like)
print(ones_like)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


<ipython-input-4-66b3ae5b4eab>:8: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  tensor_r = torch.range(start=1, end=10, step=1)


In [5]:
# Can transpose to dot multiply
t5 = torch.rand(2,3)
t6 = torch.rand(2,3)
t3_combine = t5 @ t6.T
print(t3_combine)

tensor([[0.8398, 1.0395],
        [0.6792, 0.7862]])


In [6]:
# Aggregations
t_agg = torch.rand(4,7)
t_max = t_agg.max()
t_min = t_agg.min()
t_mean = t_agg.mean()
t_sum = t_agg.sum()
print(t_agg)
print(f'Max: {t_max}')
print(f'Min: {t_min}')
print(f'Mean: {t_mean}')
print(f'Sum: {t_sum}')

tensor([[0.1513, 0.8504, 0.9002, 0.7814, 0.1849, 0.5865, 0.4589],
        [0.1647, 0.5760, 0.4420, 0.4925, 0.0296, 0.6783, 0.2306],
        [0.9689, 0.8721, 0.1968, 0.6835, 0.0916, 0.5913, 0.1226],
        [0.8681, 0.8392, 0.8609, 0.0163, 0.9933, 0.4880, 0.5990]])
Max: 0.9933382868766785
Min: 0.016260862350463867
Mean: 0.5256691575050354
Sum: 14.71873664855957


## Tensor Manipulation

All used to change the shape or dimension since we need proper shape for dot multiplication

* Reshaping: reshapes an input tensor to defined shape. It intelligently copies if needed.
* View: return a view of tensor, but doesn't actually change the input. Never copies data and is only a reference to the original.
* Stacking: combine multi tensors on top (vstack) or side-by-side (horizontal). Basically like a union in SQL
* Squeeze: removes all `1` dimensions from a tensor
* Unsqueeze: add a `1` dimension to a target tensor
* Permute: Return a view of the tensor swapped in a certain way

In [7]:
# Reshaping, the number has to match the original l*w*h*z,etc.
# https://myscale.com/blog/torch-reshape-vs-torch-view-pytorch/
# https://neuralthreads.medium.com/understanding-the-reshaping-of-a-tensor-4dd1795e12bf
x = torch.arange(1, 10) # 10 shape

print(x)
x_reshaped = x.reshape(9,1)
print(x_reshaped)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [8]:
x2 = torch.rand(2, 20, 2, 3) # 240 shape
print(x2.shape)
x2_reshaped = x2.reshape(2,5,3,2,2, 2)
print(x2_reshaped)

torch.Size([2, 20, 2, 3])
tensor([[[[[[0.0356, 0.5248],
            [0.4262, 0.0882]],

           [[0.5487, 0.1037],
            [0.6727, 0.7654]]],


          [[[0.4943, 0.0888],
            [0.9277, 0.9675]],

           [[0.1408, 0.5081],
            [0.2400, 0.0157]]],


          [[[0.2495, 0.6727],
            [0.0681, 0.6970]],

           [[0.3193, 0.5380],
            [0.6007, 0.9990]]]],



         [[[[0.0271, 0.1433],
            [0.3041, 0.0838]],

           [[0.8436, 0.4891],
            [0.5128, 0.9332]]],


          [[[0.6192, 0.2281],
            [0.0297, 0.2898]],

           [[0.6511, 0.1528],
            [0.5391, 0.6040]]],


          [[[0.1642, 0.0527],
            [0.7392, 0.9154]],

           [[0.7698, 0.4593],
            [0.8828, 0.7059]]]],



         [[[[0.2176, 0.8198],
            [0.4778, 0.9943]],

           [[0.5378, 0.2108],
            [0.9271, 0.8879]]],


          [[[0.5560, 0.6642],
            [0.9081, 0.4895]],

           [[0.4265, 0.096

In [18]:
# Stacking - basically concat for tensors
x = torch.arange(1, 10)
x_stacked = torch.stack([x, x, x, x], dim=0)
x_vstack = torch.vstack(tensors = [x,x,x])
print(x_stacked)
print(x_vstack)

x2_stacked = torch.stack([x,x,x], dim=1)
x_hstack = torch.hstack(tensors = [x,x,x])
print(x2_stacked)
print(x_hstack)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6,
        7, 8, 9])


In [32]:
# Squeezing
x = torch.arange(1,10)
x = torch.rand(10,1,1)
x_squeeze = x.squeeze()
print(x)
print(x_squeeze)

tensor([[[0.2790]],

        [[0.1668]],

        [[0.0714]],

        [[0.0627]],

        [[0.3943]],

        [[0.3729]],

        [[0.3600]],

        [[0.7054]],

        [[0.7225]],

        [[0.5834]]])
tensor([0.2790, 0.1668, 0.0714, 0.0627, 0.3943, 0.3729, 0.3600, 0.7054, 0.7225,
        0.5834])


In [36]:
# Permute - changing the order of dimensions. It is just a VIEW. Uses same memory
x = torch.rand(224, 128, 3) # height, width, color_channels
x_permute = x.permute(2, 0, 1) # color_channels, height, width
print(x.shape)
print(x_permute.shape)

torch.Size([224, 128, 3])
torch.Size([3, 224, 128])


## Selecting Data
- same as selecting data in numpy or an array of arrays

In [40]:
# Indexing
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x)
print(x[0]) # selects everything on the 0 dimension (the whole matrix)
print(x[0][1]) # selects the 2nd row of the 0 dimension
print(x[0][2][2]) # selects the 3rd cell of the 3rd row of the 0 dimesion

# use ":" to select all of a given dimension
print(x[:, 0]) # select all of 1st dim, but just select the 1st row

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([4, 5, 6])
tensor(9)
tensor([[1, 2, 3]])


In [46]:
# get all values of the 0th and 1st dim, but only index 1 of the 2nd dim
print(x[:, :, 1])

tensor([[3, 6, 9]])


In [45]:
# Geta ll values of the 0th dim, but only the 1 index value of 1st and 2nd dim
print(x[:,1,1])

tensor([5])


## NumPy & PyTorch Integration
- data in numpy -> pytorch: `torch.from_numpy(ndarray)`
- data in pytorch -> numpy: `torch.Tensor.numpy()`

In [49]:
# Numpy -> Tensor
# Default dtype for numpy: float64
# Default dtype for torch: float32

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(array)
print(tensor)
print(array.dtype)
print(tensor.dtype)

default_t = torch.arange(1.0, 8.0)
print(default_t.dtype)

# to change the dtype for a numpy array use .type
tensor2 = torch.from_numpy(array).type(torch.float32)
print(tensor2.dtype)

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
float64
torch.float64
torch.float32
torch.float32


In [61]:
# Tensor -> Numpy
# Be sure to convert tensor to 64 since numpy default is 64bit
tensor = torch.ones(7)
numpy_tensor = tensor.double().numpy()
print(tensor)
print(tensor.dtype)
print(numpy_tensor)
print(numpy_tensor.dtype)

tensor([1., 1., 1., 1., 1., 1., 1.])
torch.float32
[1. 1. 1. 1. 1. 1. 1.]
float64


## [Reproducibility](https://pytorch.org/docs/stable/notes/randomness.html)
- we want to take the randomness out of random
- Process of neural network:
  1. Start with rand numbers
  2. Manipulate using tensor operators
  3. Update the rand numbers so that they better represent the desired output
  4. Repeat step 2-3 until output is good

### Random Seed
- This creates a 'flavor' of randomness to help with reproducibility
- Essentially the seed produces a random tensor that is reproducible


In [66]:
# Create a random seed. This is the 'flavor' of random.
# So creating random numbers with '42' will always produce the same random
RANDOM_SEED = 42 # 42 is common, but you can really use anything.

# Must use the `manual_seed` method before every `.rand` function call
torch.manual_seed(RANDOM_SEED)
rand_t1 = torch.rand(3, 2, 4)
torch.manual_seed(RANDOM_SEED)
rand_t2 = torch.rand(3, 2, 4)

print(rand_t1)
print(rand_t2)
print(rand_t1 == rand_t2)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936]],

        [[0.9408, 0.1332, 0.9346, 0.5936],
         [0.8694, 0.5677, 0.7411, 0.4294]],

        [[0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])
tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936]],

        [[0.9408, 0.1332, 0.9346, 0.5936],
         [0.8694, 0.5677, 0.7411, 0.4294]],

        [[0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])
tensor([[[True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True]]])


## Running on GPU
